### ISSUE TITLE
メモリー節約モードの初期値と実際の挙動が一致していない

### ISSUE THREAD

**Issue by neofuji** [oov/aviutl_rampreview#12]
メモリー節約モードの初期値は「通常品質」と表示されていますが、
この状態でキャッシュ作成を実行すると「無圧縮」モードで生成されます。
コンボボックスを変更して以降は意図通りのモードで生成されます。

おそらくバッキングフィールドの初期化忘れだと思います。
https://github.com/oov/aviutl_rampreview/blob/c8b385200bbd68cb01ab894196bfa9038edfda0a/src/lazarus/main.pas#L419

**Comment by oov** [comment]
ありがとうございます、確かに `FResolution` の値を初期化し忘れていますね。
開発時のテスト環境ではテスト用のプロジェクトファイルを読み込んでいたために、常に `ProjectLoadProc` によって値が更新されており初期化忘れに気付かなかったようです。
